### ISSUE TITLE
Selected drop down item is not updated when the model does

### ISSUE THREAD

**Issue by evenflow58** [ClickerMonkey/SemanticUI-Angular#13]
The ignore update on the scope.$watch of the drop down box is keeping the selected value from being programmatically selected. For example if you have the following list

`````` [
 { label: 'First', id: 1 },
 { label: 'Second', id: 2}
]```
Initially setting the item to 2 works just fine. However, if you then set the item to 1 the drop down does not change.
``````

**Comment by alex88** [comment]
In my case, the first time I select a dropdown value, the model is updated, but the dropdown still shows an empty value

**Comment by alex88** [comment]
Same issue happens in demo page http://clickermonkey.github.io/SemanticUI-Angular/examples/dropdown/directives.html at `sm-dropdown-toggle / sm-dropdown-show / sm-dropdown-hide`

**Comment by damonsutherland** [comment]
@alex88 Although not exhaustively tested, the following pull request might provide some insight into what is going on: https://github.com/ClickerMonkey/SemanticUI-Angular/pull/23

**Comment by ClickerMonkey** [comment]
Closing, PR #23 was merged
