### ISSUE TITLE
pagination directive

### ISSUE THREAD

**Issue by vannim152** [ClickerMonkey/SemanticUI-Angular#20]
Hi Phil,

Just a quick question about pagination directive. Do you plan to introduce it into this repo?

**Comment by ClickerMonkey** [comment]
There are many ways to implement one visually - if you provide an example of one and maybe potential variations I can do that.

Common elements I've had in previous paginations I've developed:
- first page
- previous page
- x number of pages to left and right of current page OR a dropdown
- page size
- summary section (N out of M rows)
- next page
- last page

**Comment by vannim152** [comment]
Yes, those are critical features & components for a pagination. I would imagine the directive be like: 

`<sm-pagination 
    model="currentPage" 
    total-items="{Collection}" 
   settings="{page-size: 5, first-last-page: true}">
</sm-pagination>`

![image](https://cloud.githubusercontent.com/assets/15664980/20949274/9d48b0bc-bc6c-11e6-90fa-0873ca0f13d1.png)

**Comment by ClickerMonkey** [comment]
Sorry I dropped the ball on this, I don't have time anymore to implement any new directives for this project.
