### ISSUE TITLE
Clear dropdown in code

### ISSUE THREAD

**Issue by hossainiir** [ClickerMonkey/SemanticUI-Angular#26]
Hi, I have simple question!!
How can I clear the drop-down in controller??
I have tried with setting the model to null ,undefined , "" ,{} ,... but didn't work.
Thanks

**Comment by stevengiraldo** [comment]
I'm having the same problem.
I want to clear a form with a group of dropdown that point to same model parent.

**Comment by jansivans** [comment]
I think I have fixed this: #28

**Comment by ClickerMonkey** [comment]
Code Released:

https://github.com/ClickerMonkey/SemanticUI-Angular/releases/tag/0.2.3
