### ISSUE TITLE
I dont want Jquery on my angular App

### ISSUE THREAD

**Issue by josuevalrob** [ClickerMonkey/SemanticUI-Angular#36]
Is there any way to apply this without Jquery?

**Comment by ClickerMonkey** [comment]
Semantic UI heavily depends on jQuery - but there is another project which removed that need... It's just not as complete.

There are a few components that could work without jQuery and you won't know until you try. You just need to make sure the code `window.jQuery = window.$ = window.angular.element` runs after angular is included and before Semantic JS is included. I had a list of functions in jqlite that needed upgraded that were used in the library by certain components, but I don't recall which components needed that and which jqlite functions.
