### ISSUE TITLE
License not included in build artifacts

### ISSUE THREAD

**Issue by jimschubert** [ClickerMonkey/SemanticUI-Angular#4]
No license header is included in the gulp output for [angular-semantic-ui.min.js](https://github.com/ClickerMonkey/SemanticUI-Angular/blob/master/angular-semantic-ui.min.js) or the uncompressed output.

I'd be happy to take a look at this if it's not something in progress.

**Comment by ClickerMonkey** [comment]
It's not in progress, feel free @jimschubert!

**Comment by jimschubert** [comment]
Done and done ;)
